name: web_deploy
description: A development tool to build a web release that is GitHub Pages ready.
version: 1.0.5
repository: https://www.github.com/tytydraco/web_deploy

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  yaml: ^3.1.1

dev_dependencies:
  very_good_analysis: ^3.0.1

executables:
  web_deploy: web_deploy
